### ISSUE TITLE
Complete Landing Pages

### ISSUE THREAD

**Issue by wyattowalsh** [wyattowalsh/data-science-notes#67]
In general, Data Science Notes sections are broken into landing pages and basics pages (with more specific pages to come as folks add them).

Landing pages are a good place to host general information about the technology or technique. [The main site landing page](https://makeuseofdata.com) is a good example as it has a header image, introductory text, and helps to orient the reader.

### Here are the site's landing pages: 

- [x] **Main Landing Page** (***Current Version***) [[link to website](https://makeuseofdata.com)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/index.md)]
- [ ] **Mathematical Topics**
  - [ ] Calculus (***Needs Work***) [[link to website](https://makeuseofdata.com/mathematical_topics/calculus/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/mathematical_topics/calculus/index.md)]
  - [ ] Linear Algebra (***Needs Work***) [[link to website](https://makeuseofdata.com/mathematical_topics/linear_algebra/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/mathematical_topics/linear_algebra/index.md)]
  - [ ] Optimization (***Needs Work***) [[link to website](https://makeuseofdata.com/mathematical_topics/optimization/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/mathematical_topics/optimization/index.md)]
  - [ ] Probability (***Needs Work***) [[link to website](https://makeuseofdata.com/mathematical_topics/probability/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/mathematical_topics/probability/index.md)]
  - [ ] Statistics (***Needs Work***) [[link to website](https://makeuseofdata.com/mathematical_topics/statistics/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/mathematical_topics/statistics/index.md)]
- [ ] **Programming**
  - [ ] CI/CD (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/ci_cd/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/ci_cd/index.md)] 
  - [ ] Data Structures (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/data_structures/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/data_structures/index.md)] 
  - [ ] Frameworks (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/frameworks/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/frameworks/index.md)] 
    - [ ] Apache Hadoop (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/frameworks/apache_hadoop/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/frameworks/apache_hadoop/index.md)] 
    - [ ] Apache Spark (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/frameworks/apache_spark/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/frameworks/apache_spark/index.md)] 
    - [ ] Jupyter (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/frameworks/jupyter/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/frameworks/jupyter/index..md)] 
    - [ ] Pytorch (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/frameworks/pytorch/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/frameworks/pytorch/index.md)] 
    - [ ] TensorFlow (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/frameworks/tensorflow/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/frameworks/tensorflow/index.md)] 
  - [ ] Languages (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/index.md)] 
    - [ ] Bash (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/bash/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/bash/index.md)] 
    - [ ] C (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/c/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/c/index.md)] 
    - [ ] C++ (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/c++/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/c++/index.md)] 
    - [ ] Excel (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/excel/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/excel/index.md)] 
    - [ ] Java (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/java/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/java/index.md)] 
    - [ ] JavaScript (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/javascript/index.html)] [[link to file](data-science-notes/programming/languages/javascript/index.md)] 
    - [ ] Julia (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/julia/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/julia/index.md)] 
    - [ ] MATLAB (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/matlab/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/matlab/index)] 
    - [ ] Python (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/python/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/python/index.md)] 
    - [ ] R (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/r/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/r/index.md)] 
    - [ ] Rust (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/rust/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/rust/index.md)] 
    - [ ] SAS (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/sas/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/sas/index.md)] 
    - [ ] Scala (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/scala/index.html)] [[link to file](data-science-notes/programming/languages/scala/index.md)] 
    - [ ] SQL (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/languages/sql/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/programming/languages/sql/index.md)] 
  - [ ] Version Control (***Needs Work***) [[link to website](https://makeuseofdata.com/programming/version_control/index.html)] [[link to file](data-science-notes/programming/version_control/index.md)] 
- [ ] **Data Collection**
  - [ ] Databases (***Needs Work***) [[link to website](https://makeuseofdata.com/data_collection/databases/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/data_collection/databases/index.md)] 
- [ ] **Data Processing**
  - [ ] Cleaning (***Needs Work***) [[link to website](https://makeuseofdata.com/data_processing/cleaning/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/data_processing/cleaning/index.md)] 
  - [ ] Feature Engineering (***Needs Work***) [[link to website](https://makeuseofdata.com/data_processing/feature_engineering/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/data_processing/feature_engineering/index.md)] 
  - [ ] Feature Selection (***Needs Work***) [[link to website](https://makeuseofdata.com/data_processing/feature_selection/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/data_processing/feature_selection/index.md)] 
  - [ ] Data Imputation (***Needs Work***) [[link to website](https://makeuseofdata.com/data_processing/data_imputation/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/data_processing/data_imputation/index.md)] 
- [ ] **Visualization**
  - [ ] Python (***Needs Work***) [[link to website](https://makeuseofdata.com/visualization/python/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/visualization/python/index.md)] 
- [ ] **Machine Learning & Data Mining** 
  - [ ] Classification (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/classification/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/machine_learning_and_data_mining/classification/index.md)]  [[possible sources](https://github.com/wyattowalsh/data-science-notes/blob/master/possible_sources/classification.md)]
  - [ ] Clustering (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/clustering/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/machine_learning_and_data_mining/clustering/index.md)] 
  - [ ] Deep Learning (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/deep_learning/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/machine_learning_and_data_mining/deep_learning/index.md)] 
  - [ ] Dimensionality Reduction (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/dimensionality_reduction/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/machine_learning_and_data_mining/dimensionality_reduction/index.md)] 
  - [ ] Natural Language Processing (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/nlp/index.html)] [[link to file](data-science-notes/machine_learning_and_data_mining/nlp/index.md)] 
  - [ ] Regression (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/regression/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/machine_learning_and_data_mining/regression/index.md)] 
  - [ ] Reinforcement Learning (***Needs Work***) [[link to website](https://makeuseofdata.com/machine_learning_and_data_mining/reinforcement_learning/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/machine_learning_and_data_mining/reinforcement_learning/index.md)] 
- [ ] **Addional Topics**
  - [ ] Business Topics (***Needs Work***) [[link to website](https://makeuseofdata.com/additional_topics/business_topics/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/additional_topics/business_topics/index.md)] 
  - [ ] Exploratory Data Analysis (***Needs Work***) [[link to website](https://makeuseofdata.com/additional_topics/eda/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/additional_topics/eda/index.md)] 
  - [ ] Simulation (***Needs Work***) [[link to website](https://makeuseofdata.com/additional_topics/simulation/index.html)] [[link to file](https://github.com/wyattowalsh/data-science-notes/blob/master/data-science-notes/additional_topics/simulation/index.md)]

**Comment by Kaustubh01** [comment]
Hi, I'm Kaustubh and I'm interested in making my contributions to your project. I'm kind of new to GitHub so ill be needing a little help

**Comment by wyattowalsh** [comment]
Hey @Kaustubh01! Welcome to ***Data Science Notes*** 😊

I'm in the process of adding additional information to the issues, but happy to help out with whatever; just let me know how I may be of assistance!

**Comment by wyattowalsh** [comment]
The structure of the project has shifted a bit; check out #68 😊
